version: '3.7'

services:

  rabbit_mq:
  
    container_name: rabbit_boi
    image:
      rabbitmq:latest
    ports:
      - '5672:5672'

  
  beat:
  
    container_name: beat_boi
    build: .
    command: celery -A app.worker beat
    env_file:
      - secrets.env
    depends_on: 
      - rabbit_mq
    volumes:
      - .:/celery-app/celery-tut


  celery_tut:

    container_name: celery_boi

    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - rabbit_mq

    volumes:
      - .:/celery-app/celery-tut
    
    env_file:
      - secrets.env

    command: celery -A app.tasks worker

